[package]
name = "poseidon"
version = "0.1.0"
authors = ["kilic <kiliconu@itu.edu.tr>"]
edition = "2021"

[dependencies]
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
rand = "0.8"
group = "0.11"
subtle = { version = "2.3", default-features = false }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false }
